### PR TITLE
Fix textAlign flow relative polyfill

### LINKED ISSUE #177: textAlign processing
At https://github.com/sandflow/imscJS/blob/master/src/main/js/html.js#L1433-L1458, `tts:direction` is used to determine the mapping of `tts:textAlign` and not `context.ipd`. TTML2 says:
> The tts:textAlign attribute is used to specify a style property that defines how inline areas are aligned within a containing block area in the inline progression direction.

Is the current code correct?

### PR DESCRIPTION
**Pull request by palemieux**
Closes #177

### CODE REVIEW

File: src/main/js/html.js [hunk 1]
```diff
@@ -302,9 +284,33 @@
                 context.bpd = "rl";
 
             }
+ 
+        } else if (isd_element.kind === "p" && context.bpd === "tb") {
+
+            var pdir = isd_element.styleAttrs[imscStyles.byName.direction.qname];
 
+            context.ipd = pdir === "ltr" ? "lr" : "rl";
```
Comment (cconcolato) [inline src/main/js/html.js:292]: I'm not sure I understand why this change is necessary. Can you create an example?

Comment (palemieux) [reply src/main/js/html.js:292]: @cconcolato Even though it is not entirely clear in TTML2, `tts:direction`, when specified on `p`, is intended to override `tts:writingMode` (at least when ipd is horizontal), otherwise the following test does not work: https://github.com/w3c/imsc-tests/blob/master/imsc1/ttml/direction/Direction003.ttml . It is not clear what is the intended effect of `tts:direction` specified on `p` when the ipd is vertical -- in the case of CSS, this overrides the ipd vertically, where `ltr` means `tb` and `rtl` means `bt`.

Comment (palemieux) [reply src/main/js/html.js:292]: See https://github.com/w3c/ttml2/issues/1211
